services:
  - type: web
    name: fleetos-backend
    env: python
    region: ohio
    plan: starter # You can choose other plans like standard, pro, etc.
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fleetos-db
          property: internalConnectionString
      - key: DEBUG
        value: "False"
      - key: ALLOWED_ORIGINS
        value: "https://myfleetos.vercel.app"
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: fleetos-db
    region: ohio
    plan: starter # Recommended for production, free tier has limited connections/compute
    databaseName: fleet_db
    user: fleet_user
