"""add geofence

Revision ID: 0a0507f0f422
Revises: 384b9b1877a0
Create Date: 2026-08-19 20:08:54.981637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a0507f0f422'
down_revision: Union[str, None] = '384b9b1877a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS vehicle_geofences CASCADE")
    op.alter_column('geofences', 'coordinates',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='coordinates::json')
    op.alter_column('locations', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_account_code")
    op.add_column('vehicles', sa.Column('geofence_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_vehicles_geofence_id'), 'vehicles', ['geofence_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'geofences', ['geofence_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_geofence_id'), table_name='vehicles')
    op.drop_column('vehicles', 'geofence_id')
    op.create_unique_constraint(op.f('uq_users_account_code'), 'users', ['account_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('geofences', 'coordinates',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('vehicle_geofences',
    sa.Column('vehicle_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('geofence_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], name=op.f('vehicle_geofences_geofence_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('vehicle_geofences_vehicle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vehicle_id', 'geofence_id', name=op.f('vehicle_geofences_pkey'))
    )
    # ### end Alembic commands ###
