"""Init

Revision ID: 1316c710e59f
Revises: 
Create Date: 2026-08-25 00:29:46.347751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1316c710e59f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjusted for circular FK! ###
    # Step 1: Tables with no foreign key dependencies
    op.create_table('otp_codes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    op.create_index(op.f('ix_otp_codes_id'), 'otp_codes', ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_recording_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('account_code', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_code'), 'users', ['account_code'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    # Step 2: geofences depends on users
    op.create_table('geofences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=32), server_default='#17b385', nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofences_id'), 'geofences', ['id'], unique=False)
    op.create_index(op.f('ix_geofences_user_id'), 'geofences', ['user_id'], unique=False)

    # Step 3: vehicles depends on users and geofences.
    # active_tracking_session_id FK to tracking_sessions is added AFTER tracking_sessions is created (step 4).
    op.create_table('vehicles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('active_session_id', sa.String(length=64), nullable=True),
    sa.Column('active_tracking_session_id', sa.BigInteger(), nullable=True),
    sa.Column('last_moved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('pairing_code', sa.String(length=32), nullable=False),
    sa.Column('share_code', sa.String(length=32), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=True),
    sa.Column('geofence_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_device_id'), 'vehicles', ['device_id'], unique=True)
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicles_geofence_id'), 'vehicles', ['geofence_id'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_pairing_code'), 'vehicles', ['pairing_code'], unique=True)
    op.create_index(op.f('ix_vehicles_share_code'), 'vehicles', ['share_code'], unique=True)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)

    # Step 4: tracking_sessions depends on vehicles (now created above)
    op.create_table('tracking_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_sessions_id'), 'tracking_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_vehicle_id'), 'tracking_sessions', ['vehicle_id'], unique=False)

    # Step 5: Now that tracking_sessions exists, add the circular FK on vehicles
    op.create_foreign_key(
        'fk_vehicles_active_tracking_session_id',
        'vehicles', 'tracking_sessions',
        ['active_tracking_session_id'], ['id'],
        ondelete='SET NULL'
    )

    # Step 6: Remaining tables that depend on vehicles and tracking_sessions
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.Float(precision=9), nullable=False),
    sa.Column('longitude', sa.Float(precision=9), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_session_id'), 'locations', ['session_id'], unique=False)
    op.create_index(op.f('ix_locations_vehicle_id'), 'locations', ['vehicle_id'], unique=False)
    op.create_table('pairing_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_requests_device_id'), 'pairing_requests', ['device_id'], unique=False)
    op.create_index(op.f('ix_pairing_requests_id'), 'pairing_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pairing_requests_sender_id'), 'pairing_requests', ['sender_id'], unique=False)
    op.create_index(op.f('ix_pairing_requests_user_id'), 'pairing_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjusted for circular FK! ###
    # Reverse of upgrade: drop dependent tables first
    op.drop_index(op.f('ix_pairing_requests_user_id'), table_name='pairing_requests')
    op.drop_index(op.f('ix_pairing_requests_sender_id'), table_name='pairing_requests')
    op.drop_index(op.f('ix_pairing_requests_id'), table_name='pairing_requests')
    op.drop_index(op.f('ix_pairing_requests_device_id'), table_name='pairing_requests')
    op.drop_table('pairing_requests')
    op.drop_index(op.f('ix_locations_vehicle_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_session_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # Drop the manually created circular FK before dropping tracking_sessions
    op.drop_constraint('fk_vehicles_active_tracking_session_id', 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_tracking_sessions_vehicle_id'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_id'), table_name='tracking_sessions')
    op.drop_table('tracking_sessions')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_share_code'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_pairing_code'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_geofence_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_device_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_geofences_user_id'), table_name='geofences')
    op.drop_index(op.f('ix_geofences_id'), table_name='geofences')
    op.drop_table('geofences')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_code'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_codes_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
