"""Add geofence models

Revision ID: 384b9b1877a0
Revises: a4b18b862378
Create Date: 2026-08-19 19:17:10.987385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '384b9b1877a0'
down_revision: Union[str, None] = 'a4b18b862378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_geofence_status_geofence_id'), table_name='vehicle_geofence_status')
    op.drop_index(op.f('ix_vehicle_geofence_status_id'), table_name='vehicle_geofence_status')
    op.drop_index(op.f('ix_vehicle_geofence_status_vehicle_id'), table_name='vehicle_geofence_status')
    op.drop_table('vehicle_geofence_status')
    op.add_column('geofences', sa.Column('coordinates', sa.String(), nullable=False))
    op.drop_column('geofences', 'geometry')
    op.drop_column('geofences', 'type')
    op.alter_column('locations', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.create_index(op.f('ix_pairing_requests_sender_id'), 'pairing_requests', ['sender_id'], unique=False)
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_account_code")
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.drop_column('vehicles', 'last_active_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.create_unique_constraint(op.f('uq_users_account_code'), 'users', ['account_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_pairing_requests_sender_id'), table_name='pairing_requests')
    op.alter_column('locations', 'longitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.add_column('geofences', sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('geofences', sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('geofences', 'coordinates')
    op.create_table('vehicle_geofence_status',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('geofence_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_inside', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_checked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], name=op.f('vehicle_geofence_status_geofence_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('vehicle_geofence_status_vehicle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_geofence_status_pkey'))
    )
    op.create_index(op.f('ix_vehicle_geofence_status_vehicle_id'), 'vehicle_geofence_status', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_geofence_status_id'), 'vehicle_geofence_status', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_geofence_status_geofence_id'), 'vehicle_geofence_status', ['geofence_id'], unique=False)
    # ### end Alembic commands ###
