"""add tracking session

Revision ID: 53349f9ecaa8
Revises: 589c693559b6
Create Date: 2026-08-24 13:07:22.781366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53349f9ecaa8'
down_revision: Union[str, None] = '589c693559b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('tracking_session_id', sa.BigInteger(), nullable=True))
    op.alter_column('locations', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.create_index(op.f('ix_locations_tracking_session_id'), 'locations', ['tracking_session_id'], unique=False)
    op.create_foreign_key(None, 'locations', 'tracking_sessions', ['tracking_session_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('uq_users_account_code'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_account_code'), 'users', ['account_code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_index(op.f('ix_locations_tracking_session_id'), table_name='locations')
    op.alter_column('locations', 'longitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('locations', 'tracking_session_id')
    # ### end Alembic commands ###
