"""add geofence color

Revision ID: 589c693559b6
Revises: 0a0507f0f422
Create Date: 2026-08-24 12:46:45.298058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589c693559b6'
down_revision: Union[str, None] = '0a0507f0f422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geofences', sa.Column('color', sa.String(length=32), server_default='#17b385', nullable=False))
    op.alter_column('locations', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_account_code'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_account_code'), 'users', ['account_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('geofences', 'color')
    # ### end Alembic commands ###
