"""Add OTPCode table

Revision ID: a4b18b862378
Revises: 001_initial
Create Date: 2026-08-13 18:42:08.582343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b18b862378'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.execute("DROP INDEX IF EXISTS ix_locations_vehicle_timestamp")
    op.alter_column('users', 'account_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_account_code")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_account_code ON users (account_code)")
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'car'::character varying"))
    op.alter_column('vehicles', 'pairing_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('vehicles', 'share_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_vehicles_pairing_code ON vehicles (pairing_code)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_vehicles_share_code ON vehicles (share_code)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_vehicles_user_id ON vehicles (user_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_share_code'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_pairing_code'), table_name='vehicles')
    op.alter_column('vehicles', 'share_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('vehicles', 'pairing_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'car'::character varying"))
    op.drop_index(op.f('ix_users_account_code'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_account_code'), 'users', ['account_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'account_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.create_index(op.f('ix_locations_vehicle_timestamp'), 'locations', ['vehicle_id', sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
