"""Add tracking sessions

Revision ID: c34ebed18721
Revises: 53349f9ecaa8
Create Date: 2026-08-24 16:11:28.851842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34ebed18721'
down_revision: Union[str, None] = '53349f9ecaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('session_id', sa.BigInteger(), nullable=True))
    op.alter_column('locations', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=False)
    op.drop_index(op.f('ix_locations_tracking_session_id'), table_name='locations')
    op.create_index(op.f('ix_locations_session_id'), 'locations', ['session_id'], unique=False)
    op.drop_constraint(op.f('locations_tracking_session_id_fkey'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'tracking_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('locations', 'tracking_session_id')
    op.alter_column('tracking_sessions', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_account_code'), 'users', type_='unique')
    op.add_column('vehicles', sa.Column('active_tracking_session_id', sa.BigInteger(), nullable=True))
    op.add_column('vehicles', sa.Column('last_moved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'tracking_sessions', ['active_tracking_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'last_moved_at')
    op.drop_column('vehicles', 'active_tracking_session_id')
    op.create_unique_constraint(op.f('uq_users_account_code'), 'users', ['account_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('tracking_sessions', 'status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.add_column('locations', sa.Column('tracking_session_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_tracking_session_id_fkey'), 'locations', 'tracking_sessions', ['tracking_session_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_locations_session_id'), table_name='locations')
    op.create_index(op.f('ix_locations_tracking_session_id'), 'locations', ['tracking_session_id'], unique=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('locations', 'session_id')
    # ### end Alembic commands ###
